package com.repoinspector.core;
public enum RepoBuddyErrorCode {
    REPOBUDDY_PROJECT_NOT_FOUND, REPOBUDDY_PROJECT_AMBIGUOUS, REPOBUDDY_PROJECT_NOT_SUPPORTED,
    REPOBUDDY_IDE_NOT_RUNNING, REPOBUDDY_SCAN_FAILED, REPOBUDDY_SCAN_TIMEOUT,
    REPOBUDDY_PROJECT_INDEXING, REPOBUDDY_PROJECT_DISPOSED, REPOBUDDY_ISSUE_NOT_FOUND,
    REPOBUDDY_SCAN_NOT_FOUND, REPOBUDDY_PATH_OUTSIDE_PROJECT, REPOBUDDY_INVALID_ARGUMENT,
    REPOBUDDY_OUTPUT_LIMIT_EXCEEDED, REPOBUDDY_AUTHENTICATION_FAILED,
    REPOBUDDY_PROTOCOL_MISMATCH, REPOBUDDY_INTERNAL_ERROR
}
